name: 'Send Notification'
description: 'Sends a notification message to Slack'
inputs:
  webhook-url:
    description: 'The Slack webhook URL'
    required: true
  message:
    description: 'The message to send'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
